# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Integration tests
on:
  pull_request:
    branches: ["main"]
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test 1
        run: |
          echo "Comment on PR #${{ github.event.issue.number }}"

